/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_chibi_scheme_repl_Native */

#ifndef ANDROID_CHIBI_SCHEME_REPL_NATIVE_H
#define ANDROID_CHIBI_SCHEME_REPL_NATIVE_H 1

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_android_chibi_scheme_repl_ChibiInterpreter_init
(JNIEnv * env, jclass clazz, jstring working_dir);

JNIEXPORT void JNICALL Java_android_chibi_scheme_repl_ChibiInterpreter_release
(JNIEnv *env, jclass clazz, jlong interpreter_handle);

JNIEXPORT void JNICALL Java_android_chibi_scheme_repl_ChibiInterpreter_eval
(JNIEnv *env, jclass clazz, jlong interpreter_handle, jstring code,
 jobjectArray out_result, jbooleanArray out_error);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef ANDROID_CHIBI_SCHEME_REPL_NATIVE_H */
